
str(mpg)
qplot(displ,hwy,data=mpg,color=drv,geom=c("point","smooth")) 
qplot(drv,hwy,data=mpg,geom="boxplot",color=manufacturer) 
qplot(hwy,data=mpg,fill=drv)
qplot(hwy,data=mpg,facets=drv~.,binwidth=2)
qplot(displ, hwy, data=mpg, geom=c("point","smooth"), facets=.~drv) 
g <- qplot(mpg)
g <- ggplot(mpg, aes(displ,hwy)) 
summary(g)
g+geom_point()+geom_smooth(method="lm")+facet_grid(.~drv)+ggtitle("Swirl Rules!") 
g+geom_point(color="pink",size=4,alpha=1/2) 
g+geom_point(aes(color=drv),size=2,alpha=1/2)+geom_smooth(size=4,linetype=3,method="lm",se=FALSE) 
g+geom_point(aes(color=drv))+theme_bw(base_family="Times") 
plot(myx,myy,type="l",ylim=c(-3,3))
g <- ggplot(testdat,aes(x=myx,y=myy)) 
g+geom_line()+ylim(-3,3)
g+geom_line()+coord_cartesian(ylim=c(-3,3))
g<-ggplot(mpg,aes(x=displ,y=hwy,color=factor(year))) 
g+geom_point()+facet_grid(drv~cyl,margins=TRUE)+geom_smooth(method="lm",se=FALSE,size=2,color="black")+labs
    (x="Displacement",y="Highway Mileage",title="Swirl Rules!")


str(diamonds)
qplot(price, data=diamonds) 
range(diamonds$price)
qplot(price, data=diamonds,geom="density",color=cut)
qplot(price, data=diamonds,binwidth=18497/30,fill=cut) 
qplot(carat,price,data=diamonds,color=cut,facets=.~cut)+geom_smooth(method="lm") 
g<-ggplot(diamonds,aes(depth,price)) 
summary(g)
g+geom_point(alpha=1/3)
cutpoints<-quantile(diamonds$carat,seq(0,1,length=4),na.rm=TRUE)
cutpoints
diamonds$car2<-cut(diamonds$carat,cutpoints) 
g<-ggplot(diamonds,aes(depth,price))
g+geom_point(alpha=1/3)+facet_grid(cut~car2)+geom_smooth(method="lm",size=3,color="pink")
ggplot(diamonds,aes(carat,price))+geom_boxplot()+facet_grid(.~cut)